- cypress/integration/DefinitionEnglish.feature
- cypress/integration/DefinitionSpanish.feature
- src/components/molecules/definition/definition.jsx
Closes #19
* Using prettyUrl in place of termId if it exists for "More Info.." link
* Updated integration tests
> (#19) Use Pretty URL if it exists

- src/components/molecules/definition/definition.jsx
- src/components/molecules/definition/definition.scss
- src/components/molecules/pronunciation/pronunciation.jsx
Closes #25
* Display term name when no pronunciation exists for definition
> (#25) Term name - no pronunciation

- src/components/molecules/definition/definition.scss
Closes #20
* Added bottom margin to definition description
> (#20) Definition Box Padding

- src/utils/strings.js
Closes # 26
* Added whitespace to regex
* Updated regex
> (#26) Truncated Definition Sentence

- src/components/molecules/search-results-list/search-results-list.jsx
Closes (#33) 
Fixing the mobile view by dropdown.
> (#33) Mobie ViewBy Fix

- src/components/molecules/pronunciation/pronunciation.scss
- src/components/molecules/search-results-list/search-results-list.scss
Closes (#34) 
Closes (#35) 
https://react-app-dev.cancer.gov/sitewide-search-app/pr-41?swkeyword=myeloproliferative
> Bugfix: text wrapping issues on mobile

- cypress/integration/BestBetsSpanish.feature
- src/components/molecules/best-bet/__tests__/best-bet.test.js
- src/components/molecules/best-bet/best-bet.jsx
Closes #48
* Fixed issue with multiple BestBet content not showing up correctly
* Updated unit test to test for scenario above
> (#48) BestBet Multiple Content Mismatch

- cypress/integration/AppAnalytics/DefinitionLinkClick.feature
- cypress/integration/common/index.js
- src/components/molecules/definition/__tests__/definition.test.js
- src/components/molecules/definition/definition.jsx
Closes #46
- added event handler in the definition component
- added integration tests
- added unit test for analytics event in the definition
> (#46) Definition Link Click analytics

- cypress/integration/AppAnalytics/BestBetsLinkClick.feature
- cypress/integration/common/index.js
- package.json
- src/components/molecules/best-bet/__tests__/best-bet.test.js
- src/components/molecules/best-bet/best-bet.jsx
- src/utils/closest.js
- src/utils/index.js
- src/views/Home/__tests__/Home.en.test.js
- support/mock-data/bestbets/v1/BestBets/live/en/visual dcis.json
- added analytics handler in the bestbets component
- unit tests for analytics in home and best bets components
- integration tests
Closes #39
> (#39)  BestBets link click analytics

- cypress/integration/AppAnalytics/SearchResultsTitleClick.feature
- cypress/integration/common/index.js
- src/components/molecules/search-results-list/__tests__/result-list-item.test.js
- src/components/molecules/search-results-list/results-list-item.jsx
- src/components/molecules/search-results-list/search-results-list.jsx
Closes #43
* Added tracking event and click handler
* Added integration tests
* Updated unit tests
> (#43) Analytics: Other Search Results Click

- src/views/Home/Home.scss
Closes #57
* Added `flex-wrap: nowrap` to default view
> (#57) IE Definition Box Wrap on Large Viewports

- cypress/integration/ResultsPagerEnglish.feature
- cypress/integration/common/index.js
- src/components/molecules/search-results-list/search-results-list.jsx
- support/mock-data/Search/cgov/en/all/carcinoma_0-20.json
- support/mock-data/Search/cgov/en/all/mynci_0-20.json
Closes #53 
* When there are less results than max view by on page - hide the pager
https://react-app-dev.cancer.gov/sitewide-search-app/pr-70?cfg=0&swkeyword=mynci
> (#53) Pager Visibility for less than results

- cypress/integration/common/index.js
- src/components/molecules/search-results-list/results-list-item.jsx
> (#54) Changed Media Type to not be hyperlinked

- src/components/molecules/best-bet/best-bet.jsx
> (#58) Fixed the logic for findIndexOfLink

- src/components/molecules/no-results/no-results.jsx
- src/views/Home/__tests__/Home.en.test.js
> (#72) No Results Page fix

- src/components/molecules/best-bet/best-bet.scss
- src/components/molecules/definition/definition.scss
- src/components/molecules/no-results/no-results.jsx
- src/components/molecules/pronunciation/pronunciation.scss
- src/components/molecules/search-results-list/search-results-list.scss
- src/styles/sitewide-search.scss
- src/utils/i18n.js
- src/views/Home/__tests__/Home.en.test.js
Closes #63 
* change background image size/positions 
* update hide/show scss to fix alignment
> (#63) IE issues on Search Results Page

- src/components/molecules/definition/definition.scss
Closes #85 
*update the background color to white for the definition box
> (#85) dictionary box background color update

- src/components/molecules/search-results-list/search-results-list.scss
Closes #81
* Updated style to remove h-scrollbar
> (#81) Horizontal Scrollbar on Results

- src/components/molecules/pronunciation/pronunciation.jsx
- src/components/molecules/pronunciation/pronunciation.scss
- src/views/Home/Home.scss
Closes #74
Closes #76
* Updated DOM structure for pronunciation and styling
* Reverted audio outline
* Switched placement of styles
* Inline display for audio and key
> (#76) Term and phonetic spacing

- src/components/molecules/search-results-pager/search-results-pager.scss
Closes #78 
* Adding space in pager container / does not appear in mobile view
https://react-app-dev.cancer.gov/sitewide-search-app/pr-79/?cfg=0&swkeyword=glicosilado+de+polietileno+del+factor+de+crecimiento+y+desarrollo+del+megacariocito+humano+recombinante&page=1&pageunit=50
> (#78) Adding Margin to Pager Container

- src/components/molecules/search-results-pager/search-results-pager.jsx
Closes #89 
* Update functionality of the pager to match other sites (specifically the ending sequence)
> (#89) make pager consistent

- src/components/molecules/best-bet/best-bet.scss
Closes #94
* Updated styling for best bets
https://react-app-dev.cancer.gov/sitewide-search-app/pr-97?cfg=0&swkeyword=pact
> (#94) Bestbets bluebox width

- cypress/integration/ResultsPagerEnglish.feature
- cypress/integration/ResultsPagerSpanish.feature
- cypress/integration/common/index.js
- support/mock-data/Search/cgov/en/all/tumor_11500-20.json
- support/mock-data/Search/cgov/en/all/tumor_11520-20.json
- support/mock-data/Search/cgov/en/all/tumor_11540-20.json
- support/mock-data/Search/cgov/en/all/tumor_11560-20.json
- support/mock-data/Search/cgov/en/all/tumor_11580-20.json
> (#92)added integration test for last page of a pager

- package-lock.json
- package.json
Closes #115 
Updated axios along with listed packages:
npm update ini --depth 4
npm install axis@0.21.1
npm install --save-dev resolve-url-loader@3.1.2
> Ticket #115 Axios version update to fix high severity security warning

- .pa11yci
- package-lock.json
- package.json
Steps:
1. `nvm use v12`
2. Update `.pa11yci`
```
"chromeLaunchConfig": {
"args": [
"--no-sandbox",
"--disable-setuid-sandbox",
"--disable-dev-shm-usage"
]
}
```
3. Run `npm install --save-dev pa11y-ci@^3.0.1`
> (#122) Pa11y Issue Fix

- package-lock.json
- package.json
* `package.json` and `package-loack.json` file updates after `npm audit fix`
Closes #130
> (#130) Update npm security vulnerabilities

- package-lock.json
- package.json
(Closes #140)
- uninstalled node-sass
- installed sass
> (#140) Change out node-sass for sass

- src/components/molecules/search-results-list/search-results-list.jsx
- terms that have a dictionary definition but no search results now show the text "Results 0-0 of 0"
Closes #99
> (#99) Dictionary definition but no search results

- src/views/ErrorBoundary/ErrorPage.jsx
- src/views/ErrorBoundary/PageNotFound.jsx
- src/views/Home/Home.jsx
- name parameter in event tracking now handles both http and https protocols
Closes #126
> (#126) Name param in event tracking to handle both http and https

- package-lock.json
- package.json
* Updated `style-loader` from `0.23.1` to `2.0.0`
Closes #161
> (#161) Update style-loader to v2.0.0
